server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  client_max_body_size 80m;

  location / {
    try_files $uri $uri/ /index.html;
  }

  location /api/ {
    proxy_pass http://service:8080;
    proxy_read_timeout 300s;
    client_max_body_size 80m;
  }

  location /tiles/ {
    proxy_pass http://service:8080;
    proxy_read_timeout 60s;
  }
}
